### ISSUE TITLE
Unable to add multiple conditions using logical. 

### ISSUE THREAD

**Issue by harish-nandirajendra** [SebastianUA/terraform-aws-glue#11]
glue_trigger_predicate = [ {

  conditions =  {
      job_name         = module.glue_generic_ing_validation_pipeline.glue_job_id
      state            = var.state 
    }, 

  logical = "AND"
  
    conditions =  {
      job_name         = module.glue_generic_cur_validation_pipeline.glue_job_id
      state            = var.state
      } 
    }
  ]
  
  The piece of code does not work, am I missing anything?

**Comment by SebastianUA** [comment]
Hi @harish-nandirajendra,

Please try to use:
```
glue_trigger_predicate = [{
	
	logical = null

	conditions = {
	  job_name         = null
          state            = null
          crawler_name     = null
          crawl_state      = null
          logical_operator = null
	}
}]
```

**Comment by harish-nandirajendra** [comment]
I tried using logical at the top and mentioned my conditions after that.

Like this,

glue_trigger_predicate = [ {

logical = "AND"

conditions = {
job_name = module.glue_generic_ing_validation_pipeline.glue_job_id
state = var.state
},

conditions =  {
  job_name         = module.glue_generic_cur_validation_pipeline.glue_job_id
  state            = var.state
  } 
}
]

Still it does not work. It is only able to pick up only one condition.

**Comment by SebastianUA** [comment]
@harish-nandirajendra 

```
glue_trigger_predicate = [
	{
	
		logical = null

		conditions = {
		  job_name         = null
		      state            = null
		      crawler_name     = null
		      crawl_state      = null
		      logical_operator = null
		}
	},
	{
	
		logical = null

		conditions = {
		  job_name         = null
		      state            = null
		      crawler_name     = null
		      crawl_state      = null
		      logical_operator = null
		}
	}
]
```

**Comment by harish-nandirajendra** [comment]
Throws me the below error now,

Error: Too many list items
"Attribute supports 1 item maximum, but config has 2 declared"

**Comment by SebastianUA** [comment]
Hi @harish-nandirajendra 

I have fixed the issue. You can use the next tag - https://github.com/SebastianUA/terraform-aws-glue/releases/tag/v1.4.4
Also, I added usage to example:
```
glue_trigger_predicate = {
    logical = "AND"
    conditions = [
      {
        job_name         = "job-name-1"
        state            = null
        crawler_name     = null
        crawl_state      = null
        logical_operator = "EQUALS"
      },
      {
        job_name         = "job-name-2"
        state            = null
        crawler_name     = null
        crawl_state      = null
        logical_operator = "EQUALS"
      }
    ]
  }
```

Could you please test it and let me know if we can close this issue? :)
Thank you!

**Comment by harish-nandirajendra** [comment]
All working fine now.
Closing the issue.

Thanks so much
