### ISSUE TITLE
Error: error creating Glue Job (aws_glue_generic_cur_pipeline_v1_test): InvalidInputException: Connections list should not be null or empty.    on .terraform\modules\glue_generic_cur_pipeline_v1\glue_job.tf line 4, in resource "aws_glue_job" "glue_job":    4: resource "aws_glue_job" "glue_job"

### ISSUE THREAD

**Issue by harish-nandirajendra** [SebastianUA/terraform-aws-glue#12]
The resolution to this is to comment the "connections" line.

resource "aws_glue_job" "glue_job" {
  count = var.enable_glue_job ? 1 : 0

  name     = var.glue_job_name != "" ? lower(var.glue_job_name) : "${lower(var.name)}-glue-job-${lower(var.environment)}"
  role_arn = var.glue_job_role_arn

  description            = var.glue_job_description
  connections            = var.glue_job_connections != null && !var.enable_glue_connection ? var.glue_job_connections : concat(var.glue_job_additional_connections, [element(concat(aws_glue_connection.glue_connection.*.id, [""]), 0)])

**Comment by harish-nandirajendra** [comment]
Could you create a new version where the connections is commented?

The thing is in my project we are deployinyg the code through Jenkins. So terraform init, apply happens via Jenkins.

While testing, after terraform init if I comment that line and deploy, it works for me.

**Comment by harish-nandirajendra** [comment]
This is kind of critical mate, could you create a separate version commenting our this particular line so that I can use it?

**Comment by harish-nandirajendra** [comment]
@SebastianUA there??

**Comment by SebastianUA** [comment]
Hi @harish-nandirajendra 

Please share your main.tf file with properties. I will take a look at it

**Comment by harish-nandirajendra** [comment]
[glue_job.txt](https://github.com/SebastianUA/terraform-aws-glue/files/7174701/glue_job.txt)
[Jobs.txt](https://github.com/SebastianUA/terraform-aws-glue/files/7174702/Jobs.txt)

glue_job.tf has an attribute called connections which is of no need to me. But when I run the glue job it throws me an error stating that "connections is required". I have to go to .terraform/modules/glue..../glue_job.tf to comment the connections line. Works fine after I comment the line.

Since we are using jenkins to deploy our code, terraform init, apply happens via pipeline. I cannot step in the middle and comment the "connections" line.

Kindly help.

**Comment by harish-nandirajendra** [comment]
Mate, any update?

**Comment by SebastianUA** [comment]
Hi @harish-nandirajendra 

Please try to use:
```
module "glue_generic_cur_pipeline_v1" {
  source                     = "git@github.com:SebastianUA/terraform-aws-glue.git//?ref=master"

  enable_glue_job            = true
  glue_job_name              = ""
  // glue_job_glue_version      = var.glue_job_glue_version
  glue_job_role_arn          = module.glue_example_admin_role.iam_role_arn
  // glue_job_number_of_workers = var.glue_job_number_of_workers
  // glue_job_worker_type       = var.glue_job_worker_type
  // glue_job_timeout           = var.glue_job_timeout

  glue_job_default_arguments = {
    "--job-bookmark-option" : "job-bookmark-disable"
    "--TempDir" : "s3://aws-glue-temporary-251721600074-us-east-2/admin"
    "--SUBJOB_ID" : "1003"
  }

  glue_job_command = [
    {
      script_location = "s3://aws-glue-scripts-251721600074-us-east-2/admin/aws-glue-generic-cur-pipeline-v1"
      python_version  = 3
    }
  ]

  tags = {}
}
```
