### ISSUE TITLE
Error: Too many schema_change_policy blocks

### ISSUE THREAD

**Issue by michaelplehm** [SebastianUA/terraform-aws-glue#13]
Hi,

I try to configure a Glue crawler by setting a "schema_change_policy". 
How is the input "glue_crawler_schema_change_policy" to be filled correctly? Inputting a list of maps (default is `[]`), e.g.
```
glue_crawler_schema_change_policy = [
    {
      delete_behavior = "LOG",
      update_behavior = "UPDATE_IN_DATABASE"
    }
  ]
```
this leads to `Error: Too many schema_change_policy blocks`. 

From my point of view, it cannot be iterated by using for_each as that leads to several blocks like 
```
  schema_change_policy {
    delete_behavior = <VALUE>
  }

  schema_change_policy {
    update_behavior = <VALUE>
  }
```

Any help is appreciated. 

Thanks,
Michael

**Comment by SebastianUA** [comment]
Hi @michaelplehm,

No more than 1 "schema_change_policy" blocks are allowed.  So, you can use:
```
glue_crawler_schema_change_policy = [
    {
      delete_behavior = "LOG",
      update_behavior = "UPDATE_IN_DATABASE"
    }
  ]```

**Comment by michaelplehm** [comment]
Hi @SebastianUA,

Thanks for your fast reply.  That was exactly how I used it.

But when looking at the complete error message again, I realized now, I was not using the current master branch of the module:
```
Error: Too many schema_change_policy blocks
│ 
│   on .terraform/modules/glue/aws/modules/glue/glue_crawler.tf line 102, in resource "aws_glue_crawler" "glue_crawler":
│  102:     content {
│ 
│ No more than 1 "schema_change_policy" blocks are allowed
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/glue/aws/modules/glue/glue_crawler.tf line 103, in resource "aws_glue_crawler" "glue_crawler":
│  103:       recrawl_behavior = lookup(schema_change_policy.value, "recrawl_behavior", null)
│ 
│ An argument named "recrawl_behavior" is not expected here.
```

Sorry for the inconvenience!
