### ISSUE TITLE
Output "glue_user_defined_function_create_date" is breaking the module

### ISSUE THREAD

**Issue by michaelplehm** [SebastianUA/terraform-aws-glue#14]
Hi,

The output "glue_user_defined_function_create_date" is correctly implemented according to the Hashicorp AWS provider documentation. Unfortunately, the documentation is wrong as the code uses "create_time" instead of "create_date".
The documentation will be fixed in  AWS provider v3.71.0 (https://github.com/hashicorp/terraform-provider-aws/pull/22381) but this leads to the need of a fix at outputs.tf accordingly:

```
output "glue_user_defined_function_create_time" {
  description = "The time at which the function was created."
  value       = element(concat(aws_glue_user_defined_function.glue_user_defined_function.*.create_time, [""]), 0)
}
```

Currently, the whole module seems to be unusable due to the wrong output value. 
I am not allowed to push a new branch including this change for creation of a pull request.

Best,
Michael

**Comment by SebastianUA** [comment]
Hi @michaelplehm,

Thanks for hands your hands up. I just changed the output and for now, you can use the next tag: https://github.com/SebastianUA/terraform-aws-glue/tree/v1.4.5

Thanks

**Comment by michaelplehm** [comment]
Hi @SebastianUA,

Thanks for the quick fix. It's working perfectly now.

Best,
Michael
