### ISSUE TITLE
Crawler automation

### ISSUE THREAD

**Issue by harishtorres** [SebastianUA/terraform-aws-glue#15]
Hi, I am trying to work on an automation for glue crawlers. I am able to use for_each for the crawler names, the problem is I cannot use the same for s3_path since it will be unique to each crawler. I am trying to find a way if I can automation both the crawler_names and s3_paths?

**Comment by SebastianUA** [comment]
Hi @harishtorres 

Please share the module execution code. I will take a look at it to understand what do you want.
