### ISSUE TITLE
When enable_glue_connection is set to false (default), the connections variable is set to [""] causing InvalidInputException

### ISSUE THREAD

**Issue by meetvasu15** [SebastianUA/terraform-aws-glue#16]
I am trying to create a glue job, I don't need to create any connections here therefore I don't set the glue_job_connections variable. However the module builds a connection list anyway looking like this -> [""]. This causes a InvalidInputExcpetion. 

I think this has to do with line 11 of glue_job.tf of the module

> `connections            = var.glue_job_connections != null && !var.enable_glue_connection ? var.glue_job_connections : concat(var.glue_job_additional_connections, [element(concat(aws_glue_connection.glue_connection.*.id, [""]), 0)])  `

When glue_job_connections  is not set and enable_glue_connection is false (default), the concat function ends up generating [""] which AWS does not seem to like, it wants [] or connection var be not set at all.

A work around is to set the glue_job_connections = [] but it will be great if the module doesn't create a connection list with the empty string.

My code:

```
module "glue_etl_job" {
  source                     = "SebastianUA/glue/aws"
  name                       = var.glue_etl_job_name
  environment                = var.env
  enable_glue_job            = true
  glue_job_name              = var.glue_etl_job_name
  glue_job_role_arn          = var.glue_iam_service_role_arn
  glue_job_number_of_workers = 3
  glue_job_worker_type       = "G.1X"
  glue_job_glue_version      = "3.0"
  # enable_glue_connection     = false 
  # glue_job_connections       = [] <------- work around

  glue_job_execution_property = [
    {
      max_concurrent_runs = 1
    }
  ]
  glue_job_command = [
    {
      script_location = local.glue_script_s3_path
      name            = "glueetl"
    }
  ]
  glue_job_default_arguments = { "--job-bookmark-option" = "job-bookmark-enable" }

  enable_glue_workflow = true
  glue_workflow_name   = var.glue_etl_workflow_name
}
```

**Comment by SebastianUA** [comment]
Hi @meetvasu15 

Right, I can fix variable from `null` to `[]`.

**Comment by SebastianUA** [comment]
@meetvasu15 - Done it.

Could you please check it and let me know if I should create a new tag for you.
Thank you!

**Comment by meetvasu15** [comment]
@SebastianUA Thanks for the fast response. 

I dont think this resolves it, in this situation when I dont want to create any connections, and just create a job with your module, the condition to check if any glue_job_connections were passed to the module will lead to a false. And when you create the connection list along with the glue_job_additional_connections variable 

`

> concat(var.glue_job_additional_connections, [element(concat(aws_glue_connection.glue_connection.*.id, [""]), 0)])

`
the list that is generated will still be [""].

In my opinion, since you set the default for variable glue_job_connections  = [], you dont need to check for its length or it being null or more than 0 anymore. My code doesnt deal with glue_job_additional_connections so I cant test what the full implication of not checking the length of the list will be. May be you could just put the workaround in the readme, for situation when no connections are needed.

**Comment by meetvasu15** [comment]
+ with this latest change, my workaround will not work either, I will need to supply at least one connection.

**Comment by SebastianUA** [comment]
@meetvasu15, made a simple check. Please re-check it on your side.

**Comment by meetvasu15** [comment]
Hi @SebastianUA - thanks for providing the fix so quick. I tested my code, it works now without passing the empty connection list. We can close this issue. Appreciate your efforts!
